"""
Processed dataset generation.

Reads raw TSVs, applies multi-view normalization, and writes versioned Parquet
files with full metadata manifests. Never modifies raw data.

Output structure:
    data/processed/{version}/
        train_source1.parquet
        train_source2.parquet
        train_source3.parquet
        test_source1.parquet
        test_source2.parquet
        test_source3.parquet
        manifest.json
"""

import json
import hashlib
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import pandas as pd

from src.business_entity_resolution.data.load import load_source_tsv
from src.business_entity_resolution.data.validation import validate_schema, validate_ids_unique
from src.business_entity_resolution.normalization.text import (
    apply_name_normalization,
    apply_address_normalization,
)
from src.business_entity_resolution.utils.logging import get_logger

logger = get_logger(__name__)

SOURCE_COLUMNS = ["entity_id", "business_name", "business_address", "country"]

# Columns generated by normalization
NAME_NORM_COLS = [
    "name_norm_unicode",
    "name_norm_clean",
    "name_norm_punct",
    "name_norm_accent_fold",
]
ADDR_NORM_COLS = [
    "addr_norm_unicode",
    "addr_norm_clean",
    "addr_norm_punct",
    "addr_norm_accent_fold",
    "addr_numeric_tokens",
]


def _compute_file_hash(filepath: str) -> str:
    """Compute SHA-256 hash of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def process_source_file(
    raw_path: str,
    output_path: str,
    source_label: str,
) -> dict:
    """Process a single source TSV: normalize and write Parquet.

    Args:
        raw_path: Path to the raw TSV file.
        output_path: Path for the output Parquet file.
        source_label: Human label for logging (e.g. 'train_source1').

    Returns:
        Dict with processing metadata for this file.
    """
    t0 = time.time()
    logger.info(f"Processing {source_label}: {raw_path}")

    df = load_source_tsv(raw_path)
    raw_row_count = len(df)

    # Schema validation
    validate_schema(df, SOURCE_COLUMNS, source_label)
    validate_ids_unique(df, "entity_id", source_label)

    # Apply normalization — preserves all original columns
    df = apply_name_normalization(df, raw_col="business_name", prefix="name")
    df = apply_address_normalization(df, raw_col="business_address", prefix="addr")

    # Integrity checks
    assert len(df) == raw_row_count, (
        f"Row count changed during processing: {raw_row_count} -> {len(df)}"
    )
    assert "entity_id" in df.columns, "entity_id column missing after processing"
    assert "business_name" in df.columns, "business_name column lost during processing"
    assert "business_address" in df.columns, "business_address column lost during processing"
    assert "country" in df.columns, "country column lost during processing"

    # Write Parquet
    df.to_parquet(output_path, index=False)
    elapsed = time.time() - t0
    logger.info(f"Wrote {output_path}: {len(df)} rows, {len(df.columns)} columns in {elapsed:.1f}s")

    return {
        "source_label": source_label,
        "raw_path": raw_path,
        "raw_sha256": _compute_file_hash(raw_path),
        "output_path": output_path,
        "raw_row_count": raw_row_count,
        "output_row_count": len(df),
        "output_columns": list(df.columns),
        "processing_time_seconds": round(elapsed, 2),
    }


def build_processed_dataset(
    raw_train_dir: str = "data/raw/train",
    raw_test_dir: str = "data/raw/test",
    output_dir: str = "data/processed/v001",
    normalization_version: str = "v001",
) -> dict:
    """Build the complete processed dataset from raw TSVs.

    Args:
        raw_train_dir: Directory containing training TSVs.
        raw_test_dir: Directory containing test TSVs.
        output_dir: Directory for output Parquet files.
        normalization_version: Version label for provenance.

    Returns:
        Full manifest dict (also written to manifest.json).
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    files_to_process = [
        (f"{raw_train_dir}/train_source1.tsv", f"{output_dir}/train_source1.parquet", "train_source1"),
        (f"{raw_train_dir}/train_source2.tsv", f"{output_dir}/train_source2.parquet", "train_source2"),
        (f"{raw_train_dir}/train_source3.tsv", f"{output_dir}/train_source3.parquet", "train_source3"),
        (f"{raw_test_dir}/test_source1.tsv", f"{output_dir}/test_source1.parquet", "test_source1"),
        (f"{raw_test_dir}/test_source2.tsv", f"{output_dir}/test_source2.parquet", "test_source2"),
        (f"{raw_test_dir}/test_source3.tsv", f"{output_dir}/test_source3.parquet", "test_source3"),
    ]

    t0_total = time.time()
    file_metadata = []

    for raw_path, out_path, label in files_to_process:
        meta = process_source_file(raw_path, out_path, label)
        file_metadata.append(meta)

    total_elapsed = time.time() - t0_total

    manifest = {
        "processing_version": normalization_version,
        "creation_timestamp": datetime.now(timezone.utc).isoformat(),
        "normalization_version": normalization_version,
        "total_processing_time_seconds": round(total_elapsed, 2),
        "name_normalization_columns": NAME_NORM_COLS,
        "address_normalization_columns": ADDR_NORM_COLS,
        "files": file_metadata,
    }

    manifest_path = output_path / "manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    logger.info(f"Processing manifest written to {manifest_path}")

    return manifest
